exports.NotificationType = {
    INCOMING_GROUP_INVITE: "INCOMING_GROUP_INVITE",
    ACCEPTED_GROUP_INVITE: "ACCEPTED_GROUP_INVITE",
    DECLINED_GROUP_INVITE: "DECLINED_GROUP_INVITE",
}

exports.NotificationLinkType = {
    GROUP: "GROUP",
    USER: "USER"
}